config/routes.rb
Rails.application.routes.draw do
  resources :movements
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'clientes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/casino.rb
class Casino < ApplicationRecord
  has_many :clientes, dependent: :destroy
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  before_save :set_nombre_completo
  after_create :set_codigo

  # after_save :reindex_movements
  # before_destroy :reindex_movements

  belongs_to :casino

  has_many :movimientos_como_emisor, as: :emisor, class_name: "Movimiento"
  has_many :movimientos_como_receptor, as: :receptor, class_name: "Movimiento"

  # validates :nombre, :apellido, :codigo, presence: true
  # validates :codigo, uniqueness: true

  searchable do
    text :nombre_completo
    string :nombre_completo
    string :codigo
    string :documento
    boolean :esta_presente
    # text :emitidos do
    #   movimientos_como_emisor.map { |movimiento| movimiento.hora }
    # end
    # text :recibidos do
    #   movimientos_como_receptor.map { |movimiento| movimiento.hora }
    # end
    # join(:movimientos_como_emisor, target: Movimiento, type: :time, join: { from: :cliente_id, to: :id }, as: 'hora_e')
    # date :movimientos, multiple: true do
    #   movimientos_como_emisor.map(&:hora) + movimientos_como_receptor.map(&:hora)
    # end
  end

  # def reindex_movements
  #   Sunspot.index(movimientos)
  # end

  # protected

  def set_nombre_completo
    self.nombre_completo = [nombre, apellido].join(" ")
  end

  def set_codigo
    self.codigo = id.to_s.rjust(6, '0')
  end

end

app/models/movimiento.rb
class Movimiento < ApplicationRecord
  # after_save :reindex_cliente
  # after_destroy :reindex_cliente

  belongs_to :emisor, polymorphic: true, counter_cache: :movimientos_como_emisor_count
  belongs_to :receptor, polymorphic: true, counter_cache: :movimientos_como_receptor_count

  # searchable do
  #   text :name
  #   text :cliente do
  #     cliente.fullname
  #   end
  #
  #   float :ammount
  # end
  #
  # def reindex_cliente
  #   Sunspot.index(cliente)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    busqueda = params[:q]
    if busqueda
      @search = Cliente.search do
        fulltext busqueda[:nombre_completo] do
          fields :nombre_completo
          query_phrase_slop 1
        end

        with :documento, busqueda[:documento] if busqueda[:documento].present?
        with :codigo, busqueda[:codigo] if busqueda[:codigo].present?

        order_by :codigo, :asc
        paginate page: params[:page], per_page: 20
      end
      @clientes = @search.results
    else
      @clientes = Cliente.page(params[:page]).per(20)
    end

    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :apellido, :documento, :codigo)
    end
end

app/controllers/movimientos_controller.rb
class MovimientosController < ApplicationController
  before_action :set_movement, only: [:show, :edit, :update, :destroy]

  # GET /movimientos
  # GET /movimientos.json
  def index
    busqueda = params[:q]
    if busqueda
      @search = Movimiento.search do
        fulltext busqueda[:name]

        with(:ammount).less_than busqueda[:ammount] if busqueda[:ammount].present?
        order_by :ammount, :desc
        paginate page: params[:page], per_page: 20
      end
      @movimientos = @search.results
    else
      @movimientos = Movimiento.page(params[:page]).per(20)
    end
  end

  # GET /movimientos/1
  # GET /movimientos/1.json
  def show
  end

  # GET /movimientos/new
  def new
    @movimiento = Movimiento.new
  end

  # GET /movimientos/1/edit
  def edit
  end

  # POST /movimientos
  # POST /movimientos.json
  def create
    @movimiento = Movimiento.new(movement_params)

    respond_to do |format|
      if @movimiento.save
        format.html { redirect_to @movimiento, notice: 'Movimiento was successfully created.' }
        format.json { render :show, status: :created, location: @movimiento }
      else
        format.html { render :new }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimientos/1
  # PATCH/PUT /movimientos/1.json
  def update
    respond_to do |format|
      if @movimiento.update(movement_params)
        format.html { redirect_to @movimiento, notice: 'Movimiento was successfully updated.' }
        format.json { render :show, status: :ok, location: @movimiento }
      else
        format.html { render :edit }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimientos/1
  # DELETE /movimientos/1.json
  def destroy
    @movimiento.destroy
    respond_to do |format|
      format.html { redirect_to movements_url, notice: 'Movimiento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movement
      @movimiento = Movimiento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movement_params
      params.require(:movimiento).permit(:name, :ammount, :cliente_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clientes/_cliente.html.erb
<tr>
  <td><b><%= cliente.codigo %></b></td>
  <td><%= cliente.nombre_completo %></td>
  <td><%= cliente.tipo_documento %> <%= cliente.documento %></td>
  <td><%= cliente.esta_presente? ? 'SI' : 'NO' %></td>
  <td><%= link_to 'Show', cliente %></td>
  <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
  <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/clientes/_form.html.erb
<%= form_for(cliente) do |f| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :apellido %>
    <%= f.text_field :apellido %>
  </div>

  <div class="field">
    <%= f.label :documento %>
    <%= f.text_field :documento %>
  </div>

  <div class="field">
    <%= f.label :codigo %>
    <%= f.text_field :codigo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<%= form_for :q, url: clientes_path, method: :get, remote: true do |f| %>
  <%= f.text_field :codigo, placeholder: 'Código', autofocus: true %>
  <%= f.text_field :nombre_completo, placeholder: 'Nombre completo' %>
  <%= f.text_field :documento, placeholder: 'Documento' %>
  <%= f.submit 'Search' %>
<% end %>

<%= paginate @clientes %>

<table id="clientes">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nombre completo</th>
      <th>Documento</th>
      <th>¿Presente?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= content_tag :tbody, render(@clientes) %>
</table>

<%= paginate @clientes %>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/index.js.erb
$("#clientes tbody").html("<%= j render(@clientes) %>");
$(".pagination").html("<%= j paginate(@clientes) %>");

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre completo:</strong>
  <%= @cliente.nombre_completo %>
</p>

<p>
  <strong>Documento:</strong>
  <%= @cliente.tipo_documento %> <%= @cliente.documento %>
</p>

<p>
  <strong>Código:</strong>
  <%= @cliente.codigo %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sunspotlab</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'Clientes', clientes_path %></li>
      <li><%= link_to 'Movimientos', movements_path %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/movimientos/_form.html.erb
<%= form_for(movimiento) do |f| %>
  <% if movimiento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movimiento.errors.count, "error") %> prohibited this movimiento from being saved:</h2>

      <ul>
      <% movimiento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :ammount %>
    <%= f.text_field :ammount %>
  </div>

  <div class="field">
    <%= f.label :cliente_id %>
    <%= f.text_field :cliente_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movimientos/edit.html.erb
<h1>Editing Movimiento</h1>

<%= render 'form', movimiento: @movimiento %>

<%= link_to 'Show', @movimiento %> |
<%= link_to 'Back', movements_path %>

app/views/movimientos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movimientos</h1>

<%= form_for :q, url: request.path, method: :get do |f| %>
  <%= f.text_field :name %>
  <%= f.number_field :ammount %>
  <%= f.submit 'Search' %>
<% end %>

<%= paginate @movimientos %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ammount</th>
      <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movimientos.each do |movimiento| %>
      <tr>
        <td><%= movimiento.name %></td>
        <td><%= number_to_currency movimiento.ammount %></td>
        <td><%= movimiento.cliente.fullname %></td>
        <td><%= link_to 'Show', movimiento %></td>
        <td><%= link_to 'Edit', edit_movement_path(movimiento) %></td>
        <td><%= link_to 'Destroy', movimiento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @movimientos %>

<br>

<%= link_to 'New Movimiento', new_movement_path %>

app/views/movimientos/new.html.erb
<h1>New Movimiento</h1>

<%= render 'form', movimiento: @movimiento %>

<%= link_to 'Back', movements_path %>

app/views/movimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @movimiento.name %>
</p>

<p>
  <strong>Ammount:</strong>
  <%= @movimiento.ammount %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @movimiento.cliente %>
</p>

<%= link_to 'Edit', edit_movement_path(@movimiento) %> |
<%= link_to 'Back', movements_path %>